analytics.account={"id"\:1686217,"name"\:"AgentQA","uuid"\:"e2e9de86-5616-46f2-be64-5df257055aed","domain"\:"ac-1686217"}
analytics.integration.enable=true
analytics.onpremise.enable=true
analytics.onpremise.organization=null
analytics.onpremise.server=https\://testops.katalon.io
analytics.project={"id"\:3482979,"name"\:"AgentQA","teamId"\:3471891,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3501275,"accountId"\:null,"sampleProject"\:false,"autoIntegrate"\:false}
analytics.team={"id"\:3471891,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=false
analytics.testreport.autoupload.enable=false
onpremise.email=testqa.katalon@yahoo.com
onpremise.password=lt7kXPiIKwaWFlEwD/XoAA\=\=
