name: Katalon Mobile Automation Local Mac

on:
  push:
    branches: [ "main" ]

jobs:
  katalon-local-test:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run Katalon Test on Local Mac
      run: |
        /Applications/Katalon\ Studio.app/Contents/MacOS/katalon \
          -noSplash \
          -runMode=console \
          -projectPath="${{ github.workspace }}" \
          -retry=0 \
          -testSuitePath="Test Suites/Checkout Cart Shopping" \
          -browserType="Android" \
          -apiKey="${{ secrets.KATALON_API_KEY }}"