name: Katalon Mobile Automation Local Mac

on:
  push:
    branches: [ "main" ]

jobs:
  katalon-local-test:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run Katalon Test on Local Mac
      run: |
        '/Users/mymac/KRE/Katalon Studio Engine.app/Contents/MacOS/katalonc' \
          -noSplash \
          -runMode=console \
          -projectPath="${{ github.workspace }}" \
          -retry=0 \
          -testSuitePath='Test Suites/Checkout_Cart_Shopping' \
          -browserType='Android' \
          -apiKey='${{ secrets.KATALON_API_KEY }}'

    - name: Upload Test Reports to GitHub
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: katalon-mobile-reports
        path: ${{ github.workspace }}/Reports